from typing import Protocol
from uuid import UUID

from rps.domain.entities import Game, Player, PlayerStats
from rps.domain.rules import Move, Result


class PlayerRepository(Protocol):
    def create(self, name: str) -> Player: ...
    def get(self, player_id: UUID) -> Player | None: ...
    def get_by_name(self, name: str) -> Player | None: ...
    def list_all(self) -> list[Player]: ...


class GameRepository(Protocol):
    def create(
        self, player_id: UUID, player_move: Move, opponent_move: Move, result: Result
    ) -> Game: ...
    def get(self, game_id: UUID) -> Game | None: ...
    def list_for_player(
        self, player_id: UUID, limit: int, offset: int
    ) -> tuple[list[Game], int]: ...
    def stats_for_player(self, player_id: UUID) -> PlayerStats: ...
    def stats_for_all_players(self) -> dict[UUID, PlayerStats]: ...
